backend:
  name: test-repo

publish_mode: editorial_workflow

media_folder: 'assets'
public_folder: '/'

collections:
  - label: Home
    name: home
    files:
      - label: Home
        name: home
        file: 'home.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
